# Todo 插件配置文件
# 数据存储配置
dataFile: "todos.json"

# 界面设置
ui:
  # 最大显示条目数
  maxItems: 20
  # 是否显示已完成的项目
  showCompleted: true
  # 是否显示统计信息
  showStats: true
  # 图标主题
  iconTheme: "sf_symbols"

# 功能设置
features:
  # 是否启用搜索功能
  enableSearch: true
  # 是否启用自动保存
  autoSave: true
  # 自动保存间隔（秒）
  autoSaveInterval: 30
  # 是否启用完成提示音
  completionSound: false

# 快捷键设置（保留扩展用）
shortcuts:
  # 切换完成状态
  toggleComplete: "space"
  # 删除项目
  deleteItem: "cmd+delete"
  # 新增项目
  addItem: "cmd+enter"

# 排序设置
sorting:
  # 排序方式: "date", "alphabetical", "completion"
  method: "date"
  # 排序方向: "asc", "desc"
  direction: "desc"
  # 是否将已完成项目放在最后
  completedLast: true

# 数据管理
data:
  # 是否启用数据备份
  enableBackup: false
  # 备份间隔（天）
  backupInterval: 7
  # 最大备份文件数
  maxBackups: 5

# 高级设置
advanced:
  # 调试模式
  debugMode: false
  # 日志级别: "info", "debug", "error"
  logLevel: "info"
  # 性能模式: "fast", "balanced", "quality"
  performanceMode: "balanced"