# Todo 插件配置文件
# 这个文件定义了 Todo 插件的配置选项

# 插件是否启用
enabled: true

# 插件版本
version: "1.0.0"

# 插件设置
settings:
  # 最大显示的待办事项数量
  max_items: 10
  
  # 是否显示已完成的项目
  show_completed: true
  
  # 自动保存间隔（秒）
  auto_save_interval: 30
  
  # 数据文件名
  data_file: "todos.json"
  
  # UI 设置
  ui:
    # 使用的图标主题
    icon_theme: "sf_symbols"  # 可选值: sf_symbols, emoji
    
    # 颜色方案
    color_scheme: "auto"      # 可选值: auto, light, dark
    
    # 是否显示序号
    show_numbers: true
  
  # 快捷键设置
  shortcuts:
    # 添加新项目的快捷键
    add_item: "cmd+n"
    
    # 完成项目的快捷键
    toggle_complete: "space"
    
    # 删除项目的快捷键
    delete_item: "cmd+backspace"
  
  # 分类设置
  categories:
    - name: "工作"
      color: "#FF6B6B"
      icon: "briefcase"
    
    - name: "个人"
      color: "#4ECDC4"
      icon: "person"
    
    - name: "学习"
      color: "#45B7D1"
      icon: "book"
  
  # 提醒设置
  notifications:
    # 是否启用提醒
    enabled: true
    
    # 提醒声音
    sound: "default"
    
    # 逾期提醒
    overdue_reminder: true

# 高级设置
advanced:
  # 是否启用调试模式
  debug_mode: false
  
  # 日志级别
  log_level: "info"  # 可选值: debug, info, warn, error
  
  # 数据同步设置
  sync:
    # 是否启用云同步
    enabled: false
    
    # 同步服务
    provider: "icloud"  # 可选值: icloud, dropbox, manual
    
    # 同步间隔（分钟）
    interval: 15
