name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9' # 可根据你的项目需要调整

    - name: Build with Swift
      run: swift build -c release

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LightLauncher-app
        path: .build/release/LightLauncher

    - name: Install create-dmg
      run: brew install create-dmg

    - name: Build .app bundle
      run: bash build.sh

    - name: Create DMG
      run: create-dmg LightLauncher.app

    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: LightLauncher-dmg
        path: LightLauncher-*.dmg